# Introduction to Python 
This is a Jupyter Notebook: the blocks you see are called cells, and in our labs we will only need cells containing code (it is possible to run independently each single cell) or cells containing good looking text (you can even use $\LaTeX$ expressions e.g. $\hat{f}(\epsilon) = \int_{-\infty}^{+\infty} f(x) e^{-2 \pi i x \epsilon} dx$, double click this cell to see how).

You can run each single code cell independently from the others simply by pressing ctrl-enter in the current cell (be careful with the order you do so and recall that each time you run the cell in this way you are not deleting any variable from the memory!). Otherwise it is possible to run the entire notebook pressing the forward botton on the top (this will restart the kernel, i.e. all the variables you have defined will be lost and the entire notebook will be started from the beginning to the end).  

See https://jupyter-notebook.readthedocs.io/en/stable/notebook.html for more info on notebooks

## Python generalities

### Indentation:

In [249]:
for item in range(10):
    print('Surprisingly ' + str(item) + ' is an ', end='')
    if item % 2 == 0:
        print('even',  end='')  # this is a comment in Python
    else:
        print('odd',  end='')   # this is another comment in Python
    print(' number.')
print('Now you know even and odd numbers up to 9.')

Surprisingly 0 is an even number.
Surprisingly 1 is an odd number.
Surprisingly 2 is an even number.
Surprisingly 3 is an odd number.
Surprisingly 4 is an even number.
Surprisingly 5 is an odd number.
Surprisingly 6 is an even number.
Surprisingly 7 is an odd number.
Surprisingly 8 is an even number.
Surprisingly 9 is an odd number.
Now you know even and odd numbers up to 9.


Additional notes:
- no semicolon needed at the end of each statement.
- use # to add a comment.
- the end argument in print() replaces the default \n, i.e. the new line character.

### Python Types:

In [250]:
print(type(10))
print(type(7.3))
print(type(1+2j))
a = True
print(type(a))
print(type('Machine Learning'))
print(type(None))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'str'>
<class 'NoneType'>


### Scalar operations:

In [251]:
print(17/3)     # in python >= 3 the result will be the 5.666666666666667
print(17. / 3)  # (or 17/3.) classic division returns a float
print(17 // 3)  # floor division discards the fractional part
print(17 % 3)   # the % operator returns the remainder of the division

5.666666666666667
5.666666666666667
5
2


In [252]:
a = True
b = False
print(a and b)
print(a or b)
print(not a)

False
True
False


In [253]:
name = "Mario"
surname = "Rossi"
print(name + " " + surname)
print(name*3)
print(name == surname)

Mario Rossi
MarioMarioMario
False


### String indexing:

In [254]:
word = 'Python'   # you can define a string using both single and double quotes
print(word[0])    # character in position 0
print(word[-1])   # last character 
print(word[-2])   # second-last character
print(word[2:5])  # characters from position 2 (included) to 5 (excluded)
print(word[:2])   # characters from the beginning to position 2 (excluded)
print(word[4:])   # characters from position 4 (included) to the end
print(word[-2:])  # characters from the second-last (included) to the end

P
n
o
tho
Py
on
on


#### Remark
The start index is always included while the end is always excluded. Therefore we can write any string *s* as *s[:i] + s[i:]*

## TODO 1

In [255]:
our_course = "Machine Learning"

# Print 'ML' using characters from the variable our_course (exploiting concatenation: the plus operator)
# YOUR CODE HERE
print(our_course.split()[0][0] + our_course.split()[1][0])

ML


In [256]:
# Print only the first word in the variable our_course (i.e. 'Machine')
# YOUR CODE HERE
print(our_course.split()[0])

Machine


In [257]:
# Concatenate (with a space in between) the 4-th character in our_course variable ('h') and the first 4 characters from the second word ('Lear')
# YOUR CODE HERE
print(our_course.split()[0][3] + " " +our_course.split()[1][0:4])

h Lear


In [258]:
# Try the same 3 points using the reverse indexing
# YOUR CODE HERE
print(our_course.split()[-2][0] + our_course.split()[-1][0])
print(our_course.split()[-2])
print(our_course.split()[-2][-4] + " " + our_course.split()[-1][-8:-4])

ML
Machine
h Lear


## Containers

### Lists:
A **list** represents an ordered, mutable collection of objects (any type of Python object)
#### Remark:
You can mix and match any type of object in a list, add to it and remove from it at will

In [259]:
empty_list = []
empty_list = list() # alternative syntax

char_list = list(('a', 'b', 'c', 'd')) # conversion to list
num_list = [1, 2, 3, 4]
string_list = ['I','will','pass','ML']

# concatenation
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
print(x) # how to index in this case?

[['a', 'b', 'c'], [1, 2, 3]]


## TODO 2
Please note the difference between `our_course` (that is a `string`) and `our_course_list` (that is a `list`)

In [260]:
our_course_list = list(our_course)
print(our_course_list)

['M', 'a', 'c', 'h', 'i', 'n', 'e', ' ', 'L', 'e', 'a', 'r', 'n', 'i', 'n', 'g']


In [261]:
# Perform the same indexing as before, you can choose if normal or reverse indexing
# YOUR CODE HERE
print(our_course_list[0] + our_course_list[8])
print(our_course_list[0:7])
print(list(our_course_list[3]) + list(our_course_list[7]) + list(our_course_list[8:11]))

ML
['M', 'a', 'c', 'h', 'i', 'n', 'e']
['h', ' ', 'L', 'e', 'a']


In [262]:
# Modify the characters "M" and "L" in our_course_list to their lowercase version
# YOUR CODE HERE
print(our_course_list[0].lower() + our_course_list[8].lower())


ml


In [263]:
# Do the same with the string our_course (why do you get an error?)
# YOUR CODE HERE
print(our_course[0].lower())

m


In [264]:
# Try to access the item 'b' and the item 3 in variable x
# YOUR CODE HERE
print(x[0][1])
print(x[1][2])

b
3


### Lists (part 2):

In [265]:
int_list = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]               
int_list.append(9)  
int_list.remove(9)                  # remove the first occurrence of 9
print(int_list)

[10, 8, 7, 6, 5, 4, 3, 2, 1, 9]


In [266]:
removed_number = int_list.pop()     # return and remove the last item
print(removed_number)
print(int_list)

9
[10, 8, 7, 6, 5, 4, 3, 2, 1]


In [267]:
print(int_list[::])                 # all elements, equal to print(int_list)
print(int_list[::-1])               # all elements in reverse order
print(int_list[0:9:2])              # elements in even positions from 0 to 9

[10, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 10]
[10, 7, 5, 3, 1]


In [268]:
print(5 in int_list)                # check membership
print('hello' in 'hello world')     # membership works also for strings

True
True


### Mutability:

In [269]:
x = 5
y = x        # This means that y = x = 5
x = 9        # Now we have the x = 9 and y = 5 (y does not change!)

In [270]:
x = [1, 2, 3]
y = x        # This means that y = x = [1,2,3]
x.append(4)  # Now we have the x = [1,2,3,4] and y = [1,2,3,4] (y does change!)
y.pop()      # Now we have the x = [1,2,3] and y = [1,2,3] (x does change!)
x[1] = 123   # Now we have both x and y equal to [1, 123, 3]    

Mutable means that x now has a reference to the value of y (both of them 'point' to the same memory). Immutable means that x now has a copy of the value of y

## TODO 3

In [271]:
# Print every intermediate step of the previous cell (just copy-paste it and add a print statement for x and y after each line)
# YOUR CODE HERE
x = [1, 2, 3]
print(x)
y = x        # This means that y = x = [1,2,3]
print(y)
x.append(4)  # Now we have the x = [1,2,3,4] and y = [1,2,3,4] (y does change!)
print(x)
y.pop()      # Now we have the x = [1,2,3] and y = [1,2,3] (x does change!)
print(y)
x[1] = 123   # Now we have both x and y equal to [1, 123, 3]    
print(x)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3]
[1, 123, 3]


In [272]:
int_list = [1,2,3,4]
# Use only the methods `.append()` and `.remove()` to reverse `int_list`
# YOUR CODE HERE
int_list.append(4)
int_list.append(3)
int_list.append(2)
int_list.append(1)

int_list.remove(1)
int_list.remove(2)
int_list.remove(3)
int_list.remove(4)

print(int_list)

[4, 3, 2, 1]


### Tuples
Tuples are ordered immutable collections

**Indexing:** Same as string and lists indexing

**Membership:** Same as list membership

**Other operations:** '+' Concatenation

In [273]:
num_tuple = (1, 6) # tuple definition, using () instead of []
print(len(num_tuple))

2


#### Remark
Tuples are just like lists but they are immutable: their values cannot be changed!

**Question:** why do we need tuples if lists do more?
- Tuples are lighter and more memory efficient
- Tuples can be used as keys in a dictionary

### Dictionaries:
A dictionary (a.k.a. associative array) consists of a collection of key-value pairs. Each key-value pair maps the key to its associated value

In [274]:
name2grade = dict() # Creating an empty dictionary
name2grade = {}
name2grade['Fabio'] = 18
print(name2grade)
name2grade['Leonardo'] = 31    
print(name2grade)
name2grade['Alessandro'] = 30 
print(name2grade)

{'Fabio': 18}
{'Fabio': 18, 'Leonardo': 31}
{'Fabio': 18, 'Leonardo': 31, 'Alessandro': 30}


In [275]:
print(name2grade['Alessandro']) 
print(name2grade.keys())  
print(name2grade.values()) 
del name2grade['Fabio']   
print(name2grade.items())  

30
dict_keys(['Fabio', 'Leonardo', 'Alessandro'])
dict_values([18, 31, 30])
dict_items([('Leonardo', 31), ('Alessandro', 30)])


## Control flow

### if-elif-else
Remember to put colon (:) after the conditions (and else)

In [276]:
x = 1
if x > 2:
    print('x > 2')
elif x == 2:
    print('x = 2')
else:
    print('x < 2')
print("The value of x is: " + str(x))

x < 2
The value of x is: 1


In [277]:
grade = 27.2
course = "Calculus"
if (grade > 26) and (not (course != "ML")):
    print("Everything is good")
else:
    print("Need to study for ML!")

Need to study for ML!


### for

In [278]:
num_list = [1, 10, 42]

# These five loops print the same!
for x in num_list:
    print(x)

1
10
42


In [279]:
for x in range(3):
    print(num_list[x])

1
10
42


In [280]:
for index in range(len(num_list)):
    print(num_list[index])

1
10
42


In [281]:
for index in range(0, len(num_list), 1):    # Argument of range is: start, stop, step
    print(num_list[index])

1
10
42


In [282]:
for index, element in enumerate(num_list):  # tuple unpacking
    print('Index is: ' + str(index))
    print('Value is: ' + str(element))
    print('That is equivalent to ' + str(num_list[index]))

Index is: 0
Value is: 1
That is equivalent to 1
Index is: 1
Value is: 10
That is equivalent to 10
Index is: 2
Value is: 42
That is equivalent to 42


The same can be done with any list (regardless of its content), tuple or string

## TODO 4

In [283]:
# Modify the previous code (the 5 code cells about the `for` loop) using the following `string_list` in place of `num_list`.
string_list = list(['I','will','pass','ML'])
# YOUR CODE HERE
for index in range(0, len(string_list), 1):    # Argument of range is: start, stop, step
    print(string_list[index])

I
will
pass
ML


In [284]:
# Print the elements of `string_list` separated by spaces.
# YOUR CODE HERE
for index in range(0, len(string_list), 1):    # Argument of range is: start, stop, step
    print(string_list[index], end=' ')

I will pass ML 

#### Iterating over dictionaries
The for statement can be exploited to iterate through dictionaries too

In [285]:
grades = {30: ['Leonardo', 'Alessandro']}      # grades is a dictionary
grades[26] = ['Fabio', 'Luca']                 # adding a new key

for key in grades.keys():         
    print("Students with grade = " + str(key))
    for elem in grades[key]:
        print(elem)

Students with grade = 30
Leonardo
Alessandro
Students with grade = 26
Fabio
Luca


In [286]:
grades = {30: ['Leonardo', 'Alessandro'], 26: ['Fabio', 'Luca']}  

for key in grades.keys():        # iterate over the keys of a dict
    print("Key = " + str(key))
    
for val in grades.values():      # iterate over the values of a dict
    print("Value = " + str(val))
    
for key, val in grades.items():  # iterate over both keys and values of a dict
    print("Key: " + str(key) + "\nValue: " + str(val))    

Key = 30
Key = 26
Value = ['Leonardo', 'Alessandro']
Value = ['Fabio', 'Luca']
Key: 30
Value: ['Leonardo', 'Alessandro']
Key: 26
Value: ['Fabio', 'Luca']


## TODO 5

In [290]:
# Add to the dictionary grades your own (and possibly those of some of your friends) with an unbiased estimate of your grade
# YOUR CODE HERE
grades[31] = ['Maxmillan', 'Adolf']
grades[30] = ['Bjorn Magnus']
grades[18] = ['Nihal']

print(grades)
sum = 0
total_len = 0
for key, val in grades.items(): 
    sum += len(val)*key
    total_len += len(val)

print(sum/total_len)

{30: ['Bjorn Magnus'], 26: ['Fabio', 'Luca'], 31: ['Maxmillan', 'Adolf'], -7: ['Bjorn Magnus'], 18: ['Nihal']}
22.142857142857142


In [41]:
# Write a for loop to get the average of the grades in the ML course
# YOUR CODE HERE

### while
Flow controllers:
- break: exit the loop
- continue: go to the next iteration

In [42]:
counter = 1
while (counter < 10):
    print(counter)
    counter = counter + 1
    if counter == 5:
        break

1
2
3
4


In [43]:
counter = 1
while (counter < 10):
    counter = counter + 1
    if counter in [5, 6, 9]:
        continue
    print(counter)

2
3
4
7
8
10


## Functions

### Syntax
In Python you can:
- construct new functions during the execution of a program (using *def*)
- store functions in data structures
- pass functions as arguments to other functions
- return functions as the values of other functions

Important facts:
- all functions return a value (if no return statement is specified then None is returned)
- tuples are used to return multiple values
- functions can take positional and keyword arguments
- functions can take variable number of arguments (also no arguments)
- you can specify default arguments

In [44]:
def my_add(a, b=2):  # b is a default argument, it must follow the positional arguments 
    return a + b

def my_div(a, b):
    if b == 0:
        return 'Division by zero'
    else:
        return a / b

In [45]:
def say_hello():
    print('Hello')

In [46]:
print(my_add(1, 6))                  # positional order

7


In [47]:
print(my_add(5))                     # default values

7


In [48]:
print(my_add(a=3, b=4))              # keyword arguments
print(my_add(b=4, a=3))          

7
7


In [49]:
functions_list = [my_add, my_div]    # storing functions
inputs = [0, 1, 2, 3, 4]

functions_list[0](inputs[0])

2

In [50]:
for f in functions_list:
    for i in inputs:
        print(f(10, i))

10
11
12
13
14
Division by zero
10.0
5.0
3.3333333333333335
2.5


## TODO 6 

In [51]:
# Write the function: my_repeater(n) that calls say_hello() n times
# YOUR CODE HERE

In [52]:
# Create a dictionary with 2 keys: 'my_arithmetics' and 'my_print'.
# Insert in the first key a list containing both my_add and my_div.
# Insert in the second key a list containing the functions say_hello and my_repeater.
# YOUR CODE HERE

In [53]:
# Now call one time each function you stored in the dictionary of lists
# YOUR CODE HERE

## Importing Modules
A module is a file containing Python definitions and statements

This means that we can import in our script functions written by others in order to improve our code. In this course we will need:
- numpy: https://numpy.org/
- scipy: https://docs.scipy.org/doc/scipy/reference/
- sklearn: https://scikit-learn.org/stable/

### NumPy
NumPy is a very optimized array-processing package. Moreover it presents a sintax very similar to MATLAB (it will be very intuitive for you).

Let's introduce the main object in NumPy: **ndarray** object
- Table of elements (usually numbers) of the same type
- The dimensions are called axes
- The number of axes is called rank

In [54]:
import numpy as np       # imports numpy with alias np, therefore to call a function you will write np.function_you_want()

arr = np.zeros((3, 4))   # this creates an array of zeros of 3 rows and 4 columns
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
from numpy import ones   # this import only the function you want (no reference to numpy is necessary anymore)

arr = ones((3, 4))       # this creates an array of ones 3 times 4
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [56]:
a = np.array([1, 2, 3])                 # single row vector
b = np.array([[1, 2, 3], [4, 5, 6]])    # 2 times 3 ndarray (i.e. matrix)
c = np.eye(4)                           # 4 times 4 identity matrix
d = np.random.random((2, 4))            # 2 times 4 random matrix of floats in the interval [0, 1)

print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.90650048 0.05129041 0.21773436 0.8067637 ]
 [0.9468113  0.57292582 0.70324958 0.55180824]]


#### Indexing in NumPy (the same of before)

In [57]:
print(d[:, :])      # whole ndarray, equal to print(d)
print(d[1, 1])      # element in the second row and second column
print(d[:, 0:2])    # the first 2 columns
print(d[:, 1:1])    # doesn't print anything since the slice is on the same index
print(d[:, 1:-1])   # second and third column
print(d[0, 1:])     # from second to last elements of the first row 

[[0.90650048 0.05129041 0.21773436 0.8067637 ]
 [0.9468113  0.57292582 0.70324958 0.55180824]]
0.5729258240562443
[[0.90650048 0.05129041]
 [0.9468113  0.57292582]]
[]
[[0.05129041 0.21773436]
 [0.57292582 0.70324958]]
[0.05129041 0.21773436 0.8067637 ]


#### Access properties of ndarrays

In [58]:
d = np.random.random((2,4)) 
print(d.ndim)  # array dimensions (axes)
print(d.shape) # shape of the array (note it is a tuple)
print(d.size)  # total number of elements of the array

2
(2, 4)
8


#### Creating ndarrays and reshaping

In [59]:
f = np.arange(0, 30, 5)            # sequence of integers from 0 (included) to 30 (excluded) with step 5
print(f)

[ 0  5 10 15 20 25]


In [60]:
g = np.linspace(0, 5, 10)          # sequence of 10 values evenly spaced in the interval [0, 5]
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [61]:
listarr = np.array([1, 2, 3])      # converts the list into an array
print(type(listarr))

<class 'numpy.ndarray'>


In [62]:
arr = np.random.random((3, 4))
newarr = arr.reshape(2, 2, 3)      # reshape array from 3x4 to 2x2x3
print(newarr)

[[[0.66937747 0.48563808 0.16468917]
  [0.57570159 0.933029   0.85778907]]

 [[0.33554617 0.46807992 0.9991358 ]
  [0.3349397  0.60565624 0.15654121]]]


In [63]:
fltarr = arr.flatten()             # collapse to 1 dimension
print(fltarr)

[0.66937747 0.48563808 0.16468917 0.57570159 0.933029   0.85778907
 0.33554617 0.46807992 0.9991358  0.3349397  0.60565624 0.15654121]


#### Stacking and splitting ndarrays

In [64]:
a, b = np.zeros((2, 2)), np.ones((2, 2))  # note the double assignment
c = [5, 6]
print(a)
print(b)
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[5, 6]


In [65]:
print(np.vstack((a, b)))          # Vertical stacking

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [66]:
print(np.hstack((a, b)))          # Horizontal stacking

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [67]:
print(np.column_stack((a, c)))    # Stacking columns

[[0. 0. 5.]
 [0. 0. 6.]]


In [68]:
print(np.concatenate((a, b), 1))  # Concatenate along axis 1 (same as column_stack)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [69]:
print(np.hsplit(a, 2))            # Horizontal splitting

[array([[0.],
       [0.]]), array([[0.],
       [0.]])]


In [70]:
print(np.vsplit(a, 2))            # Vertical splitting

[array([[0., 0.]]), array([[0., 0.]])]


## TODO 7

In [71]:
# Write a function my_random(a, b, c) with three arguments, which outputs a one-dimensional array of length c, where each entry is uniformly distributed between a and b
# YOUR CODE HERE

In [72]:
# Assume you pass the exam (i.e. 18<=grade<=30). By making use of my_random, draw two samples of possible grades, take the better one, convert it into an integer and print it
# YOUR CODE HERE